title: Jamplate
email: jamplate@cufy.org
description: >- # this means to ignore newlines until "baseurl:"
  Jamplate is a C-Style pre-processor. Although it is a C-Style, this does not mean it is
  following the C standard. This pre-processor has almost the same expected behaviour as a
  standard C pre-processors with some features added and some missing.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: Jamplate

markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      favicon: '/assets/ico/jamplate.ico'
      title: 'Jamplate'

github:
  owner_name: Cufy
  owner_url: https://github.com/cufyorg

emails:
  cmail: jamplate@cufy.org
  gmail: cufyorg@gmail.com

include:
  - pages
  - javadoc