theme: jekyll-theme-slate
title: Jamplate
description: C-Style moderen pre-processor

author: LSafer
organization-name: Cufy
organization-link: cufy.org

footer_content: Copyrights 2020-2021 Cufy

gh_edit_link: false


github:
  is_project_page: true
  repository_url: https://github.com/jamplate/jamplate.github.io
  owner_url: https://github.com/jamplate
  owner_name: Jamplate
