theme: jekyll-theme-slate
title: Jamplate
description: C-Style moderen pre-processor

author: LSafer
organization-name: Cufy
organization-link: cufy.org

footer_content: Copyrights 2020-2021 Cufy

gh_edit_link: false


github:
  is_project_page: false
